version: "3.9"
volumes:
  # 適宜名前変更
  vue-project-node-modules:
    name: vue-project-node-modules
  project-db-testing-volume:
    name: project-db-testing-volume

networks:
  project-network:
    name: ${PROJECT_NETWORK}

services:
  # 適宜名前変更
  project-proxy:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "${PROXY_TCP_PORT}:${PROXY_PORT}"
    depends_on:
      - ${BACKEND_CONTAINER_NAME}
      - ${FRONTEND_CONTAINER_NAME}
    volumes:
      - ./docker/web/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=Asia/Tokyo
    networks:
      - ${PROJECT_NETWORK}
    
  project-frontend:
    build:
      context: .
      dockerfile: ./docker/vue/Dockerfile
    networks:
      - ${PROJECT_NETWORK}
    volumes:
      - ./frontend:/var/www
      - vue-project-node-modules/var/www/node_modules
    command: sh -c "yarn install && yarn serve"

  project-backend:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    env_file:
      - .env
    volumes:
      - ./backend:/var/www/
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - ${DB_CONTAINER_NAME}
    networks:
      - ${PROJECT_NETWORK}
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

  project-db:
    image: mysql:8.0
    networks:
      - ${PROJECT_NETWORK}
    ports:
      - ${DB_TCP_PORT}:${DB_PORT}
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: 'Asia/Tokyo'
    command: --default-authentication-plugin=mysql_native_password
  
  project-db-testing:
    image: mysql:8.0
    networks:
      - ${PROJECT_NETWORK}
    ports:
      - ${DB_TESTING_TCP_PORT}:${DB_PORT}
    volumes:
      - project-db-testing-volume:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_TESTING_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_TESTING_DATABASE}
      MYSQL_USER: ${DB_TESTING_USERNAME}
      MYSQL_PASSWORD: ${DB_TESTING_PASSWORD}
      TZ: 'Asia/Tokyo'
    ## ログをターミナルに標準出力する
    command:  >
      bash -c '
      touch /var/log/general.log &&
      chown mysql:mysql /var/log/general.log &&
      tail -f /var/log/general.log &
      /entrypoint.sh mysqld
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --general-log=true
      --general-log-file=/var/log/general.log
      --default-authentication-plugin=mysql_native_password
      '
    logging:
      options:
        max-size: "10k"
        max-file: "5"
