version: "3.9"
volumes:
  # 適宜名前変更
  vue-project-node-modules:
    name: vue-project-node-modules

networks:
  project-network:
    name: project-network

services:
  project-proxy:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    container_name: project-proxy
    ports:
      - "8088:80"
    depends_on:
      - project-backend
      - project-frontend
    volumes:
      - ./docker/web/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      # - "chat-demo-socket:/var/run/php-fpm/"
      # - ./docker/web/proxy-php.conf:/usr/local/apache2/conf/extra/proxy-php.conf
    environment:
      - TZ=Asia/Tokyo
    networks:
      - project-network
    
  project-frontend:
    build:
      context: .
      dockerfile: ./docker/vue/Dockerfile
    container_name: project-frontend
    networks:
      - project-network
    volumes:
      - ./frontend:/var/www
      - vue-project-node-modules/var/www/node_modules
    command: sh -c "yarn install && yarn serve"

  project-backend:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: project-backend
    volumes:
      # - "chat-demo-socket:/var/run/php-fpm/"
      - ./backend:/var/www/
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - project-db
    networks:
      - project-network
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=project-db
      - DB_PORT=3306
      - DB_DATABASE=project_db
      - DB_USERNAME=project_local
      - DB_PASSWORD=project_local

  project-db:
    image: mysql:8.0
    container_name: project-db
    networks:
      - project-network
    ports:
      - 43306:3306
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: project_local
      MYSQL_DATABASE: project_db
      MYSQL_USER: project_local
      MYSQL_PASSWORD: project_local
      TZ: 'Asia/Tokyo'
    command: --default-authentication-plugin=mysql_native_password
